spring:
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        dialect.storage_engine: innodb
        format_sql: true
    show-sql: true
  datasource:
    hikari:
      max-lifetime: 58000
    url: jdbc:mysql://127.0.0.1:3306/subway?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: masterpw
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

logging:
  level:
    root: DEBUG
