spring:
  profiles:
    active: prod
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        dialect.storage_engine: innodb
        format_sql: true
    show-sql: true
  datasource:
    hikari:
      max-lifetime: 58000
    url: jdbc:mysql://192.168.255.105:3306/subway?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: masterpw
  cache:
    type: redis
  redis:
    host: 192.168.255.105
    port: 6379
